// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client_extras.proto

// Protobuf Java Version: 3.25.0
package edu.cmu.cs.roundtrip.protos;

public final class ClientExtras {
  private ClientExtras() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AnnotationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:client.AnnotationData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes frame_data = 1;</code>
     * @return The frameData.
     */
    com.google.protobuf.ByteString getFrameData();

    /**
     * <code>string annotation_text = 2;</code>
     * @return The annotationText.
     */
    java.lang.String getAnnotationText();
    /**
     * <code>string annotation_text = 2;</code>
     * @return The bytes for annotationText.
     */
    com.google.protobuf.ByteString
        getAnnotationTextBytes();
  }
  /**
   * Protobuf type {@code client.AnnotationData}
   */
  public  static final class AnnotationData extends
      com.google.protobuf.GeneratedMessageLite<
          AnnotationData, AnnotationData.Builder> implements
      // @@protoc_insertion_point(message_implements:client.AnnotationData)
      AnnotationDataOrBuilder {
    private AnnotationData() {
      frameData_ = com.google.protobuf.ByteString.EMPTY;
      annotationText_ = "";
    }
    public static final int FRAME_DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString frameData_;
    /**
     * <code>bytes frame_data = 1;</code>
     * @return The frameData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFrameData() {
      return frameData_;
    }
    /**
     * <code>bytes frame_data = 1;</code>
     * @param value The frameData to set.
     */
    private void setFrameData(com.google.protobuf.ByteString value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      frameData_ = value;
    }
    /**
     * <code>bytes frame_data = 1;</code>
     */
    private void clearFrameData() {

      frameData_ = getDefaultInstance().getFrameData();
    }

    public static final int ANNOTATION_TEXT_FIELD_NUMBER = 2;
    private java.lang.String annotationText_;
    /**
     * <code>string annotation_text = 2;</code>
     * @return The annotationText.
     */
    @java.lang.Override
    public java.lang.String getAnnotationText() {
      return annotationText_;
    }
    /**
     * <code>string annotation_text = 2;</code>
     * @return The bytes for annotationText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAnnotationTextBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(annotationText_);
    }
    /**
     * <code>string annotation_text = 2;</code>
     * @param value The annotationText to set.
     */
    private void setAnnotationText(
        java.lang.String value) {
      java.lang.Class<?> valueClass = value.getClass();
  
      annotationText_ = value;
    }
    /**
     * <code>string annotation_text = 2;</code>
     */
    private void clearAnnotationText() {

      annotationText_ = getDefaultInstance().getAnnotationText();
    }
    /**
     * <code>string annotation_text = 2;</code>
     * @param value The bytes for annotationText to set.
     */
    private void setAnnotationTextBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      annotationText_ = value.toStringUtf8();

    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code client.AnnotationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData, Builder> implements
        // @@protoc_insertion_point(builder_implements:client.AnnotationData)
        edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationDataOrBuilder {
      // Construct using edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes frame_data = 1;</code>
       * @return The frameData.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getFrameData() {
        return instance.getFrameData();
      }
      /**
       * <code>bytes frame_data = 1;</code>
       * @param value The frameData to set.
       * @return This builder for chaining.
       */
      public Builder setFrameData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setFrameData(value);
        return this;
      }
      /**
       * <code>bytes frame_data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameData() {
        copyOnWrite();
        instance.clearFrameData();
        return this;
      }

      /**
       * <code>string annotation_text = 2;</code>
       * @return The annotationText.
       */
      @java.lang.Override
      public java.lang.String getAnnotationText() {
        return instance.getAnnotationText();
      }
      /**
       * <code>string annotation_text = 2;</code>
       * @return The bytes for annotationText.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getAnnotationTextBytes() {
        return instance.getAnnotationTextBytes();
      }
      /**
       * <code>string annotation_text = 2;</code>
       * @param value The annotationText to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationText(
          java.lang.String value) {
        copyOnWrite();
        instance.setAnnotationText(value);
        return this;
      }
      /**
       * <code>string annotation_text = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnnotationText() {
        copyOnWrite();
        instance.clearAnnotationText();
        return this;
      }
      /**
       * <code>string annotation_text = 2;</code>
       * @param value The bytes for annotationText to set.
       * @return This builder for chaining.
       */
      public Builder setAnnotationTextBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAnnotationTextBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:client.AnnotationData)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "frameData_",
              "annotationText_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\n\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData> parser = PARSER;
          if (parser == null) {
            synchronized (edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:client.AnnotationData)
    private static final edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData DEFAULT_INSTANCE;
    static {
      AnnotationData defaultInstance = new AnnotationData();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AnnotationData.class, defaultInstance);
    }

    public static edu.cmu.cs.roundtrip.protos.ClientExtras.AnnotationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AnnotationData> PARSER;

    public static com.google.protobuf.Parser<AnnotationData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
